language: objective-c
before_script:
- ./scripts/update-bundle.sh
script:
- xctool -workspace TravisExample.xcworkspace -scheme TravisExample -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
- xctool test -workspace TravisExample.xcworkspace -scheme TravisExampleTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
env:
  global:
  - APP_NAME="TravisExample"
  - 'DEVELOPER_NAME="iPhone Distribution: Mattes Groeger"'
  - PROFILE_NAME="TravisExample_Ad_Hoc"
  - INFO_PLIST="TravisExample/TravisExample-Info.plist"
  - BUNDLE_DISPLAY_NAME="Travis Example CI"